local api = require("richclip.api")

describe("api tests", function()
    it("selection_to_html", function()
        local buf_id = vim.api.nvim_create_buf(false, false)
        vim.api.nvim_set_current_buf(buf_id)
        vim.api.nvim_buf_set_lines(0, 0, 0, false, { "abc", "def" })
        vim.fn.setpos("'<", { 0, 1, 1 })
        vim.fn.setpos("'>", { 0, 2, 3 })

        local html_lines = api.selection_to_html()
        assert.equals("<html>", html_lines[1])
        assert.equals("<head>", html_lines[2])
        assert.equals('<meta charset="UTF-8">', html_lines[3])
        assert.equals('</head>', html_lines[4])
        assert.equals('<body>', html_lines[5])
        assert.equals('<div style="background-color:#000000;color:#ffffff">', html_lines[6])
        assert.equals('<pre>abc<br>def<br></pre>', html_lines[7])
        assert.equals('</div>', html_lines[8])
        assert.equals('</body>', html_lines[9])
        assert.equals('</html>', html_lines[10])
    end)
end)
